version: '3.8'

# Production overrides for docker-compose.yml
services:
  postgres:
    restart: always
    environment:
      POSTGRES_DB: stockapp
      POSTGRES_USER: aman
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Remove port exposure for security in production
    # ports: []

  backend:
    restart: always
    environment:
      DATABASE_URL: postgresql://aman:${POSTGRES_PASSWORD}@postgres:5432/stockapp
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      FINNHUB_API_KEY: ${FINNHUB_API_KEY}
      GROQ_API_KEY: ${GROQ_API_KEY}
      DEBUG: "False"
    # Remove volume mount in production
    volumes: []
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  frontend:
    restart: always
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

  redis:
    restart: always
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-}
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
